// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDELs8KW_uNdDFJH2_zGC98oEpvSmkZH4Q',
    appId: '1:981163576593:web:6c44fe257f0810f13ed0b0',
    messagingSenderId: '981163576593',
    projectId: 'spendwise-5a18c',
    authDomain: 'spendwise-5a18c.firebaseapp.com',
    storageBucket: 'spendwise-5a18c.firebasestorage.app',
    measurementId: 'G-E3TRPKD3PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC47GWRyKuqDq-iSPHHYcDcy9Kcw0p3Nsc',
    appId: '1:981163576593:android:152eb50c730c09d83ed0b0',
    messagingSenderId: '981163576593',
    projectId: 'spendwise-5a18c',
    storageBucket: 'spendwise-5a18c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVlXTfs1aWjHB5aq1EhdGRM0beFou7CzU',
    appId: '1:981163576593:ios:34bd893e28bf8d883ed0b0',
    messagingSenderId: '981163576593',
    projectId: 'spendwise-5a18c',
    storageBucket: 'spendwise-5a18c.firebasestorage.app',
    iosBundleId: 'com.evenlogix.spendwise',
  );
}
